# Numpy

In [ ]:
'''Numpy is the core library for scientific computing in Python. 
It provides a high-performance multidimensional array object, and tools for working with these arrays. '''

# Numpy Cheat Sheet

[Numpy Cheat Sheet - One Page](https://github.com/m-peker/Python-NumPy-Basics/blob/master/Numpy_Python_Cheat_Sheet.pdf)

# Importing

In [1]:
import numpy as np

# Numpy Basics

In [17]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])  # 1*15 vector

print(array.shape) # Array dimensions

a = array.reshape(3,5) # Reshape, but don’t change data
print("shape: ",a.shape)
print("dimension: ", a.ndim) # Number of array dimensions
print("data type: ",a.dtype.name) # Data type of array elements
print("size: ",a.size) # Number of array elements
print("type: ",type(a))

array1 = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
zeros = np.zeros((3,4)) # Create an array of zeros

zeros[0,0] = 5
print(zeros)

np.ones((3,4)) # Create an array of ones

np.empty((2,3)) # Create an empty array

a = np.arange(10,50,5) # Create an array of evenly   spaced values (step value)
print(a)

a = np.linspace(10,50,20) # Create an array of evenly   spaced values (number of samples)
print(a)

print("--------------------------------------")
# Asking for help
np.info(np.ndarray.dtype)

(15,)
shape:  (3, 5)
dimension:  2
data type:  int32
size:  15
type:  <class 'numpy.ndarray'>
[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20 25 30 35 40 45]
[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]
--------------------------------------
Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Numpy Basic Operations

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Arithmetic Operations

print(a+b) # Addition
print(a-b) # Subtraction
print(np.sin(a)) # Print sines of an array
print(np.sqrt(a)) # Square root
print(np.square(a)) # a**2
print(np.add(a,a)) # Addition

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

# element wise prodcut
print(a*b)

# matrix prodcut
a.dot(b.T)

print(np.exp(a)) # Exponentiation
print(np.log(a)) # Element-wise natural logarithm 
a = np.random.random((5,5))

print("---------------------------------------------")
# Aggregate Functions

print(a.sum()) # Array-wise sum
print(a.max()) # Maximum value of an array row
print(a.min()) # Array-wise minimum value 
print(a.sum(axis=0)) # Sum of an array row
print(a.sum(axis=1)) # Sum of an array column
print(a.mean()) # Mean
print(np.std(b)) # Standard deviation
print("---------------------------------------------")

[5 7 9]
[-3 -3 -3]
[0.84147098 0.90929743 0.14112001]
[1.         1.41421356 1.73205081]
[1 4 9]
[2 4 6]
[[ 1  4  9]
 [16 25 36]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
---------------------------------------------
12.064518151526936
0.9942886453470896
0.04331169219877329
[1.45513768 2.5552267  2.49008022 2.9697473  2.59432624]
[2.63022154 2.45264171 1.97606707 2.44767641 2.55791142]
0.48258072606107744
1.707825127659933
---------------------------------------------


# Indexing and Slicing

In [24]:
import numpy as np
array = np.array([1,2,3,4,5,6,7])   #  vector dimension = 1
print("Array: ",array)
print(array[0]) # Select the element at the zero index

print(array[0:4]) # Select items at index 0, 1, 2 and 3

reverse_array = array[::-1] # Reversed array
print(reverse_array)

print("--------------------------------------------------")

array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array 1: ", array1)
print(array1[1,1]) # Select items at row 1 in column 1
print(array1[:,1])
print(array1[1,1:4]) 
print(array1[-1,:])
print(array1[:,-1])

Array:  [1 2 3 4 5 6 7]
1
[1 2 3 4]
[7 6 5 4 3 2 1]
--------------------------------------------------
Array 1:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


# Shape Manipulation

In [50]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n", array)

# Transposing Array
print("Transpose of array :\n", array.T) 

# Changing Array Shape
a = array.ravel() # Flatten the array
array2 = a.reshape(3,3) # Reshape, but don’t change data

# Stacking Arrays
array3 = np.array([[1,2],[3,4]])
array4 = np.array([[-1,-2],[-3,-4]])

# Veritical Combining
array5 = np.vstack((array3,array4))
print("Veritical Combining: \n",array5)
# Horizontal Combining
array6 = np.hstack((array3,array4))
print("Horizontal Combining: \n",array6)

# Different Combining Technique
np.concatenate((array3,array4),axis=0) # Veritical Combining
np.concatenate((array3,array4),axis=1) # Horizontal Combining

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of array :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Veritical Combining: 
 [[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]
Horizontal Combining: 
 [[ 1  2 -1 -2]
 [ 3  4 -3 -4]]


array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

# Convert and Copy Array

In [51]:
# Convert

liste = [1,2,3,4]   # list

array = np.array(liste) # np.array

liste2 = list(array)

a = np.array([1,2,3])

# Copy Array: These operations are incorrect. Because when you change the contents of one array, the other arrays will be affected.
b = a 
b[0] = 5
c = a 

# Copy Array: These operations are correct. 
d =  np.array([1,2,3])
e = d.copy()
f = d.copy()